name: build

on:
  push:
    branches:
      - v1
  schedule:
      - cron: '15 * * * *'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]
        composer-argument: [ ' --prefer-lowest ', '' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP with PCOV
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer update ${{ matrix.composer-argument }} --prefer-dist --no-progress --no-interaction

    - name: Run tests
      run: vendor/bin/phpunit -c ./phpunit.xml
      env:
        STORAGEZONE: ${{ secrets.STORAGEZONE }}
        APIKEY: ${{ secrets.APIKEY }}

    - name: Upload to PCOV
      run: bash <(curl -s https://codecov.io/bash)
